In [1]:
import numpy as np

In [2]:
a=np.array([0,2,3])

In [5]:
a.shape


(3,)

In [11]:
b=np.array([[1,2,3],[4,5,6]])

In [12]:
b.shape


(2, 3)

In [13]:
b.ndim

2

In [14]:
b.size

6

In [15]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
b[1]

array([4, 5, 6])

In [18]:
b[1,0]

np.int64(4)

In [19]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b[0]=np.array([1,1,1])

In [23]:
b


array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b[0:2]

array([[1, 1, 1],
       [4, 5, 6]])

In [25]:
b[:,:1]

array([[1],
       [4],
       [7]])

In [26]:
c=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) 

In [27]:
c.sum()

np.int64(45)

In [28]:
c.mean()


np.float64(5.0)

In [29]:
c.var()

np.float64(6.666666666666667)

In [31]:
c.sum(axis=1)

array([ 6, 15, 24])