In [3]:
import numpy as np

a=np.arange(4)


In [5]:
a

array([0, 1, 2, 3])

In [6]:
a+10

array([10, 11, 12, 13])

In [8]:
a+=10

In [9]:
a

array([20, 21, 22, 23])

boolean arrays also called masks

In [11]:
a[[True,False,True,False]]

array([20, 22])

In [12]:
a>=2

array([ True,  True,  True,  True])

In [16]:
a=np.arange(4)

In [17]:
a

array([0, 1, 2, 3])

In [20]:
a[a>=3]

array([3])

In [21]:
a>=3

array([False, False, False,  True])

In [22]:
a=np.random.randint(100,size=(3,3))

In [23]:
a

array([[34,  1, 66],
       [ 9, 26, 67],
       [56, 75, 75]], dtype=int32)

In [24]:
a>30

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [26]:
a[a>20]

array([34, 66, 26, 67, 56, 75, 75], dtype=int32)